import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Playfair_Display, Raleway } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const playfair = Playfair_Display({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'], variable: '--font-playfair' })
const raleway = Raleway({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'], variable: '--font-raleway' })



export const metadata: Metadata = {
  title: 'Wavy Layo Portfolio',
  description: 'Generated by WavyLayo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${playfair.variable} ${raleway.variable}`}>
      <body className="font-[var(--font-raleway)]">{children}</body>
    </html>
  )
}
